# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180130_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book_author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='app01.Author'),
        ),
        migrations.DeleteModel(
            name='Book_Author',
        ),
    ]
