# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='shixz', max_length=32),
            preserve_default=False,
        ),
    ]
